namespace Tips.ApiMessage.Models
{
    // RFC 7807
    // https://tools.ietf.org/html/rfc7807

    // REST API Error Handling — Problem Details Response by Guy Levin
    // https://dzone.com/articles/rest-api-error-handling-problem-details-response

    public class RF7807Notification
    {
        /// "type" (string) - A URI reference [RFC3986] that identifies the
        /// problem type.This specification encourages that, when
        /// dereferenced, it provide human-readable documentation for the
        /// problem type (e.g., using HTML [W3C.REC-html5-20141028]).  When
        /// this member is not present, its value is assumed to be
        /// "about:blank".
        public string Type { get; set; }

        /// <summary>
        /// "title" (string) - A short, human-readable summary of the problem
        /// type.It SHOULD NOT change from occurrence to occurrence of the
        /// problem, except for purposes of localization(e.g., using
        /// proactive content negotiation; see[RFC7231], Section 3.4).
        /// </summary>
        public string Title { get; set; }

        /// <summary>
        /// "status" (number) - The HTTP status code ([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.
        /// https://tools.ietf.org/html/rfc7231#section-3.4
        /// </summary>
        public int Status { get; set; }

        /// <summary>
        /// "detail" (string) - A human-readable explanation specific to this occurrence of the problem.
        /// https://tools.ietf.org/html/rfc7807
        /// </summary>
        public string Detail { get; set; }

        /// <summary>
        /// "instance" (string) - A URI reference that identifies the specific
        /// occurrence of the problem.It may or may not yield further
        /// information if dereferenced.
        /// </summary>
        public string Instance { get; set; }
    }
}
